### ISSUE TITLE
Failed to decode non-ASCII text

### ISSUE THREAD

**Issue by kakyoism** [iluvcapra/wavinfo#10]
## Repro

- In Reaper, import audio files that embed UTF-8 file paths containing non-ASCII characters
- Render files with bext enabled in Render dialog: This embeds the path to the Reaper project (/path/to/路径/我的.rpp) into bext
- Use `wavinfo` to create a reader, 

```
reader = wavinfo.WaveInfoReader('/path/to/my.wav')
```

## Observed

This generates errors
```
Unhandled exception:
Traceback (most recent call last):
  File "F:\my.py", line 44, in main
    self._extract_rpp_path()
  File "F:\my.py", line 55, in _extract_rpp_path
    reader = wavinfo.WavInfoReader(self.args.path)
  File "F:\.venv\lib\site-packages\wavinfo\wave_reader.py", line 59, in __init__
    self.bext = self._get_bext(f, encoding=bext_encoding)
  File "F:\.venv\lib\site-packages\wavinfo\wave_reader.py", line 117, in _get_bext
    return WavBextReader(bext_data, encoding) if bext_data else None
  File "F:\.venv\lib\site-packages\wavinfo\wave_bext_reader.py", line 26, in __init__
    self.description = sanitize_bytes(unpacked[0])
  File "F:\.venv\lib\site-packages\wavinfo\wave_bext_reader.py", line 22, in sanitize_bytes
    decoded = trimmed.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 35: ordinal not in range(128)
```

## Expected

- `wavinfo` should support arbitrary text codec or at least UTF-8

**Comment by iluvcapra** [comment]
I'm sortof torn on this one, the EBU spec is pretty clear that the description field has to be ASCII.
