### ISSUE TITLE
Raspbian: libxslt.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by victorromeo** [iluvcapra/wavinfo#5]
Received the following fault on a clean install Raspbian.

uname -a 
Linux xxxxx 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/wavinfo/__init__.py", line 7, in <module>
    from .wave_reader import WavInfoReader
  File "/home/pi/.local/lib/python3.7/site-packages/wavinfo/wave_reader.py", line 13, in <module>
    from .wave_ixml_reader import WavIXMLFormat
  File "/home/pi/.local/lib/python3.7/site-packages/wavinfo/wave_ixml_reader.py", line 2, in <module>
    from lxml import etree as ET
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
```

**Comment by victorromeo** [comment]
Fixed by running command: 
**sudo apt install libxslt-dev**
